spring.application.name=shipping-service
server.port=8087

# ================= DATABASE =================

spring.datasource.url=jdbc:postgresql://ep-shy-art-a1xzcdm4-pooler.ap-southeast-1.aws.neon.tech:5432/shiprocket?sslmode=require
spring.datasource.password=npg_Jp2a6XMmGcKs
spring.datasource.username=neondb_owner
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ================= FLYWAY =================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

# ================= SHIPROCKET =================

shiprocket.email=hellomunchz@gmail.com
shiprocket.password=RuYf5H@k!qjZY7xfbtXKP^tYk4MU#S1p

# ================= SERVICE DISCOVERY =================

eureka.client.enabled=false
spring.cloud.discovery.enabled=false