spring.application.name=shipping-service
server.port=8087

# ================= DATABASE =================

spring.datasource.url=jdbc:postgresql://postgres:5432/shippingdb
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=munchzuser
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ================= FLYWAY =================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

# ================= SHIPROCKET =================

shiprocket.email=${SHIPROCKET_EMAIL}
shiprocket.password=${SHIPROCKET_PASSWORD}

# ================= SERVICE DISCOVERY =================

eureka.client.enabled=false
spring.cloud.discovery.enabled=false