version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: munchzuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  api-gateway:
    build:
      context: .
      dockerfile: Backend/api-gateway/api-gateway/Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=568627977658-72dbv6fjkkh7np5bt1q5gmn0216tc3t4.apps.googleusercontent.com
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-profile-service
      - product-service
      - order-service
      - stock-service
      - review-service
      - coupon-service
      - payment-service
      - shipping-service

  auth-service:
    build: ./Backend/auth-service/auth-service
    container_name: auth-service
    depends_on:
      - postgres
    expose:
      - "8081"
    env_file:
      - .env
    environment:
      MAIL_USERNAME: sairamadoddi@gmail.com
      MAIL_PASSWORD: fcxl alrt wwwx mkrc

  user-profile-service:
    build: ./Backend/user-profile-service/user-profile-service
    container_name: user-profile-service
    depends_on:
      - postgres
    expose:
      - "8082"
    env_file:
      - .env

  product-service:
    build: ./Backend/product-service
    container_name: product-service
    depends_on:
      - postgres
    expose:
      - "8083"
    env_file:
      - .env

  order-service:
    build: ./Backend/order-service
    container_name: order-service
    depends_on:
      - postgres
    expose:
      - "9090"
    env_file:
      - .env

  stock-service:
    build: ./Backend/stock-service/stock-inventry-service
    container_name: stock-service
    depends_on:
      - postgres
    expose:
      - "8050"
    env_file:
      - .env

  coupon-service:
    build: ./Backend/coupon-service
    container_name: coupon-service
    depends_on:
      - postgres
    expose:
      - "8060"
    env_file:
      - .env

  payment-service:
    build: ./Backend/payment-service
    container_name: payment-service
    depends_on:
      - postgres
    expose:
      - "9092"
    env_file:
      - .env

  review-service:
    build: ./Backend/review-service
    container_name: review-service
    depends_on:
      - postgres
    expose:
      - "9095"
    env_file:
      - .env

  shipping-service:
    build: ./Backend/shiprocket-shipping-service
    container_name: shipping-service
    restart: always
    expose:
      - "8087"
    env_file:
      - .env


volumes:
  postgres-data:
