version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=sairamadoddi@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: munchzuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  api-gateway:
    build:
      context: .
      dockerfile: Backend/api-gateway/api-gateway/Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=568627977658-72dbv6fjkkh7np5bt1q5gmn0216tc3t4.apps.googleusercontent.com
    container_name: api-gateway
    env_file:
      - .env
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.munchz.rule=Host(`gomunchz.com`) || Host(`www.gomunchz.com`)"
      - "traefik.http.routers.munchz.entrypoints=websecure"
      - "traefik.http.routers.munchz.tls.certresolver=myresolver"
      - "traefik.http.services.munchz.loadbalancer.server.port=8080"
    depends_on:
      - auth-service
      - user-profile-service
      - product-service
      - order-service
      - stock-service
      - review-service
      - coupon-service
      - payment-service
      - shipping-service

  auth-service:
    build: ./Backend/auth-service/auth-service
    container_name: auth-service
    depends_on:
      - postgres
    expose:
      - "8081"
    env_file:
      - .env
    environment:
      MAIL_USERNAME: sairamadoddi@gmail.com
      MAIL_PASSWORD: fcxl alrt wwwx mkrc

  user-profile-service:
    build: ./Backend/user-profile-service/user-profile-service
    container_name: user-profile-service
    depends_on:
      - postgres
    expose:
      - "8082"
    env_file:
      - .env

  product-service:
    build: ./Backend/product-service
    container_name: product-service
    depends_on:
      - postgres
    expose:
      - "8083"
    env_file:
      - .env

  order-service:
    build: ./Backend/order-service
    container_name: order-service
    depends_on:
      - postgres
    expose:
      - "9090"
    env_file:
      - .env

  stock-service:
    build: ./Backend/stock-service/stock-inventry-service
    container_name: stock-service
    depends_on:
      - postgres
    expose:
      - "8050"
    env_file:
      - .env

  coupon-service:
    build: ./Backend/coupon-service
    container_name: coupon-service
    depends_on:
      - postgres
    expose:
      - "8060"
    env_file:
      - .env

  payment-service:
    build: ./Backend/payment-service
    container_name: payment-service
    depends_on:
      - postgres
    expose:
      - "9092"
    env_file:
      - .env
    environment:
      - RZP_K=rzp_live_SOfmd9G29HMEuL
      - RZP_S=rRVf9tna2lCD9w6apZVr4pYk

  review-service:
    build: ./Backend/review-service
    container_name: review-service
    depends_on:
      - postgres
    expose:
      - "9095"
    env_file:
      - .env

  shipping-service:
    build: ./Backend/shiprocket-shipping-service
    container_name: shipping-service
    restart: always
    expose:
      - "8087"
    env_file:
      - .env



# networks:
#   default:
#     external:
#       name: traefik-public


volumes:
  postgres-data:

