#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE authdb;
    CREATE DATABASE productdb;
    CREATE DATABASE orderdb;
    CREATE DATABASE stockdb;
    CREATE DATABASE coupondb;
    CREATE DATABASE paymentdb;
    CREATE DATABASE reviewdb;
    CREATE DATABASE shippingdb;
    CREATE DATABASE subadmindb;
    GRANT ALL PRIVILEGES ON DATABASE authdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE productdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE orderdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE stockdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE coupondb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE paymentdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE reviewdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE shippingdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE subadmindb TO "$POSTGRES_USER";
EOSQL
