spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=false
jwt.secret=${JWT_SECRET}

# ===============================
# ROUTES (DOCKER MODE)
# ===============================

# AUTH
spring.cloud.gateway.routes[9].id=auth-service
spring.cloud.gateway.routes[9].uri=http://auth-service:8081
spring.cloud.gateway.routes[9].predicates[0]=Path=/auth/**

# PRODUCT
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://product-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/api/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# ORDER
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://order-service:9090
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/api/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# STOCK
spring.cloud.gateway.routes[3].id=stock-service
spring.cloud.gateway.routes[3].uri=http://stock-service:8050
spring.cloud.gateway.routes[3].predicates[0]=Path=/stock/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# COUPON
spring.cloud.gateway.routes[4].id=coupon-service
spring.cloud.gateway.routes[4].uri=http://coupon-service:8060
spring.cloud.gateway.routes[4].predicates[0]=Path=/coupon/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

# PAYMENT
spring.cloud.gateway.routes[5].id=payment-service
spring.cloud.gateway.routes[5].uri=http://payment-service:9092
spring.cloud.gateway.routes[5].predicates[0]=Path=/payment/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

# USER PROFILE
spring.cloud.gateway.routes[6].id=user-profile-service
spring.cloud.gateway.routes[6].uri=http://user-profile-service:8082
spring.cloud.gateway.routes[6].predicates[0]=Path=/userprofile/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

# REVIEW
spring.cloud.gateway.routes[7].id=review-service
spring.cloud.gateway.routes[7].uri=http://review-service:9095
spring.cloud.gateway.routes[7].predicates[0]=Path=/reviews/**

# SHIPROCKET
spring.cloud.gateway.routes[8].id=shipping-service
spring.cloud.gateway.routes[8].uri=http://shipping-service:8087
spring.cloud.gateway.routes[8].predicates[0]=Path=/shipping/**


# ===============================
# CORS
# ===============================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=https://www.gomunchz.com,https://gomunchz.com
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

# ===============================
# CODEC (FIX 413)
# ===============================
spring.codec.max-in-memory-size=10MB
