spring.application.name=user-profile-service
server.port=8082

spring.datasource.url=jdbc:postgresql://ep-shy-art-a1xzcdm4-pooler.ap-southeast-1.aws.neon.tech/Munchz-User-Profile-Service?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000


#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
